# -*- coding: utf-8 -*-
"""Buisness_Insights_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkISMcT06iaZkSze-07gW9eb-HvtITg_
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('marketing_campaign_dataset (1).csv', encoding='latin1')

print("Rows and Columns:", df.shape)

# Show first 5 rows
print(df.head())

print("Missing values in each column:")
print(df.isnull().sum())

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

print("Clean data shape:", df.shape)
print("Column names:", df.columns.tolist())

# Convert 'acquisition_cost' and 'roi' to numeric types
df['acquisition_cost'] = df['acquisition_cost'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)
df['roi'] = pd.to_numeric(df['roi'], errors='coerce')

roi_by_channel = df.groupby('channel_used')[['acquisition_cost', 'roi']].mean().reset_index()

roi_by_channel = roi_by_channel.sort_values('roi', ascending=False)

print("ROI by Channel:")
print(roi_by_channel)

conv_by_channel = df.groupby('channel_used')['conversion_rate'].mean().reset_index()

conv_by_channel = conv_by_channel.sort_values('conversion_rate', ascending=False)

print("Conversion Rate by Channel:")
print(conv_by_channel)

channel_summary = df.groupby('channel_used').agg(
    total_spend = ('acquisition_cost', 'sum'),
    avg_roi = ('roi', 'mean')
).reset_index()

x = range(len(channel_summary))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))


ax.bar(x, channel_summary['total_spend'], width, label='Total Spend', color='tomato')
ax.bar([i + width for i in x], channel_summary['avg_roi'], width, label='Avg ROI', color='steelblue')


ax.set_xticks([i + width/2 for i in x])
ax.set_xticklabels(channel_summary['channel_used'], fontsize=12)

ax.set_title('Total Spend vs Average ROI by Channel', fontsize=14, fontweight='bold')
ax.set_ylabel('Amount')
ax.legend()

plt.tight_layout()
plt.show()

# Green bar = positive ROI, Red bar = negative ROI
colors = ['green' if x > 0 else 'red' for x in roi_by_channel['roi']]

plt.figure(figsize=(10, 6))
plt.bar(roi_by_channel['channel_used'], roi_by_channel['roi'], color=colors)

plt.axhline(0, color='black', linewidth=0.8, linestyle='--')

plt.title('Average ROI by Marketing Channel', fontsize=14, fontweight='bold')
plt.xlabel('Channel')
plt.ylabel('ROI (%)')

plt.tight_layout()
plt.show()

funnel_data = {
    'Stage': ['Impressions', 'Clicks', 'Engagement', 'Conversions'],
    'Count': [
        df['impressions'].sum(),
        df['clicks'].sum(),
        df['engagement_score'].sum(),
        df['conversion_rate'].sum()
    ]
}

funnel_df = pd.DataFrame(funnel_data)

plt.figure(figsize=(8, 6))
plt.barh(funnel_df['Stage'], funnel_df['Count'],
         color=['#4e79a7', '#f28e2b', '#e15759', '#76b7b2'])

plt.xlabel('Count')
plt.title('Marketing Funnel — Impressions to Conversions', fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

sns.barplot(data=conv_by_channel, x='channel_used', y='conversion_rate', palette='coolwarm')

plt.title('Conversion Rate by Channel (%)', fontsize=14, fontweight='bold')
plt.xlabel('Channel')
plt.ylabel('Conversion Rate (%)')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 7))

numeric_df = df[['acquisition_cost', 'roi', 'conversion_rate',
                  'clicks', 'impressions', 'engagement_score']]

sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')

plt.title('Correlation Heatmap of Marketing Metrics', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

final_summary = df.groupby('channel_used').agg(
    total_spend        = ('acquisition_cost', 'sum'),   # total money spent
    avg_roi            = ('roi', 'mean'),                # average ROI %
    avg_conversion     = ('conversion_rate', 'mean'),   # average conversion %
    total_clicks       = ('clicks', 'sum'),             # total clicks
    total_impressions  = ('impressions', 'sum'),        # total impressions
    avg_engagement     = ('engagement_score', 'mean')   # average engagement
).reset_index()

final_summary = final_summary.sort_values('avg_roi', ascending=False)

print(" FINAL MARKETING CHANNEL SUMMARY ")
print(final_summary.to_string(index=False))