# -*- coding: utf-8 -*-
"""Buisness_Insights_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkISMcT06iaZkSze-07gW9eb-HvtITg_
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('marketing_campaign_dataset.csv', encoding='latin1')

print("Rows and Columns:", df.shape)
print(df.head())

print("Missing values in each column:")
print(df.isnull().sum())

df.dropna(inplace=True)

df.drop_duplicates(inplace=True)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print("Clean data shape:", df.shape)
print("Column names:", df.columns.tolist())

df['spend'] = df['acquisition_cost'].replace({r'\$': '', r',': ''}, regex=True).astype(float)
df['revenue'] = df['spend'] * (df['roi'] / 100 + 1)
df['roi'] = ((df['revenue'] - df['spend']) / df['spend']) * 100

roi_by_channel = df.groupby('channel_used')[['spend', 'revenue', 'roi']].mean().reset_index()
roi_by_channel = roi_by_channel.sort_values('roi', ascending=False)

print("ROI by Channel:")
print(roi_by_channel)

conv_by_channel = df.groupby('channel_used')['conversion_rate'].mean().reset_index()

conv_by_channel = conv_by_channel.sort_values('conversion_rate', ascending=False)

print("Conversion Rate by Channel:")
print(conv_by_channel)

channel_summary = df.groupby('channel_used')[['spend', 'revenue']].sum().reset_index()
x = range(len(channel_summary))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))

ax.bar(x, channel_summary['spend'], width, label='Spend', color='tomato')
ax.bar([i + width for i in x], channel_summary['revenue'], width, label='Revenue', color='steelblue')

ax.set_xticks([i + width/2 for i in x])
ax.set_xticklabels(channel_summary['channel_used'], fontsize=12)

ax.set_title('Total Spend vs Revenue by Channel', fontsize=14, fontweight='bold')
ax.set_ylabel('Amount')
ax.legend()

plt.tight_layout()
plt.show()

colors = ['green' if x > 0 else 'red' for x in roi_by_channel['roi']]

plt.figure(figsize=(10, 6))
plt.bar(roi_by_channel['channel_used'], roi_by_channel['roi'], color=colors)

plt.axhline(0, color='black', linewidth=0.8, linestyle='--')

plt.title('Average ROI by Marketing Channel', fontsize=14, fontweight='bold')
plt.xlabel('Channel')
plt.ylabel('ROI (%)')

plt.tight_layout()
plt.show()

funnel_data = {
    'Stage': ['Impressions', 'Clicks'],
    'Count': [
        df['impressions'].sum(),
        df['clicks'].sum()
    ]
}

funnel_df = pd.DataFrame(funnel_data)

plt.figure(figsize=(8, 6))
plt.barh(funnel_df['Stage'], funnel_df['Count'],
         color=['#4e79a7', '#f28e2b'])

plt.xlabel('Count')
plt.title('Marketing Funnel — Impressions to Clicks', fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

sns.barplot(data=conv_by_channel, x='channel_used', y='conversion_rate', palette='coolwarm')

plt.title('Conversion Rate by Channel (%)', fontsize=14, fontweight='bold')
plt.xlabel('Channel')
plt.ylabel('Conversion Rate (%)')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 7))

numeric_df = df[['spend', 'revenue', 'clicks', 'impressions', 'roi', 'conversion_rate']]
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')

plt.title('Correlation Heatmap of Marketing Metrics', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

final_summary = df.groupby('channel_used').agg(
    total_spend = ('spend', 'sum'),
    total_revenue = ('revenue', 'sum'),
    avg_roi = ('roi', 'mean'),
    avg_conversion_rate = ('conversion_rate', 'mean')
).reset_index()

final_summary = final_summary.sort_values('avg_roi', ascending=False)

print("FINAL MARKETING CHANNEL SUMMARY ")
print(final_summary.to_string(index=False))