# -*- coding: utf-8 -*-
"""Data cleaning and preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjOsaRSgIQHaD6pqTWRFhilNgdMf96LH
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('Global_Superstore2.csv', encoding='latin1')

df.head()

print("Dataset Shape:", df.shape)

print(df.columns)

print(df.isnull().sum())

df.info()

df['Postal Code'].fillna('Unknown', inplace=True)

df.dropna(thresh=10, inplace=True)

print("Missing values handled successfully.")

df.drop_duplicates(inplace=True)

print("Duplicate rows removed successfully.")

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

print("Date columns converted successfully.")

df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')

df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

print("Numeric columns converted successfully.")

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

print("Column names cleaned successfully.")

print("Final Dataset Shape:", df.shape)

print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nData Types:\n")
print(df.dtypes)

df.to_csv('cleaned_global_superstore.csv', index=False)

print("Cleaned dataset saved successfully.")

files.download('cleaned_global_superstore.csv')